### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function

### ISSUE THREAD

**Issue by mryraghi** [VikramTiwari/geo-from-ip#55]
Getting this error while deploying using AWS Codebuild:
```
  > geo-from-ip@2.0.0 postinstall /usr/src/smartbite-server/node_modules/geo-from-ip
  > cross-env DEBUG=geo-from-ip:* node lib/update.js
  
  [91minternal/util.js:220
      throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'Function');
      ^
  
  TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function
      at Object.promisify (internal/util.js:220:11)
      at Object.<anonymous> (/usr/src/smartbite-server/node_modules/geo-from-ip/lib/update.js:7:29)
      at Module._compile (internal/modules/cjs/loader.js:654:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
      at Module.load (internal/modules/cjs/loader.js:566:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
      at Function.Module._load (internal/modules/cjs/loader.js:498:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
      at startup (internal/bootstrap/node.js:201:19)
      at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

I know this is related to this line in `node_modules/geo-from-ip/lib/update.js:7:29`:
`const streamPipeline = util.promisify(require("stream").pipeline);`.

Any idea why 'stream' is undefined?

**Comment by VikramTiwari** [comment]
Hey! Sorry about the delayed reply. Did you find a fix for this? If not, could you share the node.js and npm version that were used in AWS Codebuild? Thanks!
