### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by gigallo** [VikramTiwari/geo-from-ip#66]
Hi

I'm trying to add the library in my website project, but when i run "npm install --save geo-from-ip --verbose" i see this stacktrace:
`npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--save',
npm verb cli   'geo-from-ip',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.13.7
npm info using node@v14.15.4
npm verb npm-session e2b8d1595f930215
npm http fetch GET 200 https://registry.npmjs.org/geo-from-ip 107ms (from cache)
npm timing stage:loadCurrentTree Completed in 16925ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 140ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 16547ms
npm http fetch GET 200 https://registry.npmjs.org/maxmind-db-reader 254ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/targz 671ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/node-fetch 675ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/big-integer 15ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ip-address 64ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/cliff 310ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/cli 315ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash.merge 379ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/jsbn 389ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash.find 383ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/sprintf 394ms (from cache)
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
npm http fetch GET 304 https://registry.npmjs.org/glob 79ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/minimatch 83ms (from cache)
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm http fetch GET 304 https://registry.npmjs.org/sigmund 192ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lru-cache 195ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/winston 180ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/colors 184ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/eyes 186ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/pkginfo 30ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/async 305ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/stack-trace 304ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/cycle 309ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/lodash._basefind 27ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/lodash._basefindindex 28ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash.keys 71ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash.isarray 78ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash._baseeach 768ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash._basecallback 783ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash._bindcallback 169ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash._baseisequal 174ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash.pairs 744ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash.istypedarray 105ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash._getnative 315ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash.isarguments 316ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash.isplainobject 463ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash._arraycopy 475ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash._createassigner 472ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash.toplainobject 481ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash.keysin 1045ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash._arrayeach 1051ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash._isiterateecall 79ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash.restparam 87ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash._basefor 729ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/lodash._basecopy 302ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-fs 103ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp 185ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/pump 410ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/chownr 424ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/tar-stream 445ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer-alloc 601ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bl 605ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fs-constants 613ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/to-buffer 625ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readable-stream 637ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/string_decoder 167ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer-fill 377ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/buffer-alloc-unsafe 404ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 37781ms
npm timing stage:loadIdealTree Completed in 60094ms
npm timing stage:generateActionsToTake Completed in 739ms
npm verb correctMkdir /Users/gmgallo/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/gmgallo/.npm/_locks/staging-a2520ced5a2e0b11.lock for /Users/gmgallo/Lavoro/Progetti/workspace/Gynnico/gynnicoweb/node_modules/.staging
npm timing audit submit Completed in 3018ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 3018ms
npm timing audit body Completed in 2ms
npm timing action:extract Completed in 6024ms
npm timing action:finalize Completed in 758ms
npm timing action:refresh-package-json Completed in 1590ms
npm info lifecycle big-integer@1.6.48~preinstall: big-integer@1.6.48
npm info lifecycle buffer-alloc-unsafe@1.1.0~preinstall: buffer-alloc-unsafe@1.1.0
npm info lifecycle buffer-fill@1.0.0~preinstall: buffer-fill@1.0.0
npm info lifecycle buffer-alloc@1.2.0~preinstall: buffer-alloc@1.2.0
npm info lifecycle lru-cache@2.7.3~preinstall: lru-cache@2.7.3
npm info lifecycle colors@1.0.3~preinstall: colors@1.0.3
npm info lifecycle cycle@1.0.3~preinstall: cycle@1.0.3
npm info lifecycle eyes@0.1.8~preinstall: eyes@0.1.8
npm info lifecycle fs-constants@1.0.0~preinstall: fs-constants@1.0.0
npm info lifecycle lodash._arraycopy@3.0.0~preinstall: lodash._arraycopy@3.0.0
npm info lifecycle lodash._arrayeach@3.0.0~preinstall: lodash._arrayeach@3.0.0
npm info lifecycle lodash._basecopy@3.0.1~preinstall: lodash._basecopy@3.0.1
npm info lifecycle lodash._basefind@3.0.0~preinstall: lodash._basefind@3.0.0
npm info lifecycle lodash._basefindindex@3.6.0~preinstall: lodash._basefindindex@3.6.0
npm info lifecycle lodash._basefor@3.0.3~preinstall: lodash._basefor@3.0.3
npm info lifecycle lodash._bindcallback@3.0.1~preinstall: lodash._bindcallback@3.0.1
npm info lifecycle lodash._getnative@3.9.1~preinstall: lodash._getnative@3.9.1
npm info lifecycle lodash._isiterateecall@3.0.9~preinstall: lodash._isiterateecall@3.0.9
npm info lifecycle lodash.isarguments@3.1.0~preinstall: lodash.isarguments@3.1.0
npm info lifecycle lodash.isarray@3.0.4~preinstall: lodash.isarray@3.0.4
npm info lifecycle lodash.istypedarray@3.0.6~preinstall: lodash.istypedarray@3.0.6
npm info lifecycle lodash.keys@3.1.2~preinstall: lodash.keys@3.1.2
npm info lifecycle lodash._baseeach@3.0.4~preinstall: lodash._baseeach@3.0.4
npm info lifecycle lodash._baseisequal@3.0.7~preinstall: lodash._baseisequal@3.0.7
npm info lifecycle lodash.keysin@3.0.8~preinstall: lodash.keysin@3.0.8
npm info lifecycle lodash.isplainobject@3.2.0~preinstall: lodash.isplainobject@3.2.0
npm info lifecycle lodash.pairs@3.0.1~preinstall: lodash.pairs@3.0.1
npm info lifecycle lodash._basecallback@3.3.1~preinstall: lodash._basecallback@3.3.1
npm info lifecycle lodash.find@3.2.1~preinstall: lodash.find@3.2.1
npm info lifecycle lodash.restparam@3.6.1~preinstall: lodash.restparam@3.6.1
npm info lifecycle lodash._createassigner@3.1.1~preinstall: lodash._createassigner@3.1.1
npm info lifecycle lodash.toplainobject@3.0.0~preinstall: lodash.toplainobject@3.0.0
npm info lifecycle lodash.merge@3.3.2~preinstall: lodash.merge@3.3.2
npm info lifecycle jsbn@0.0.0~preinstall: jsbn@0.0.0
npm info lifecycle pkginfo@0.3.1~preinstall: pkginfo@0.3.1
npm info lifecycle sigmund@1.0.1~preinstall: sigmund@1.0.1
npm info lifecycle minimatch@0.3.0~preinstall: minimatch@0.3.0
npm info lifecycle glob@3.2.11~preinstall: glob@3.2.11
npm info lifecycle cli@0.6.6~preinstall: cli@0.6.6
npm info lifecycle sprintf@0.1.5~preinstall: sprintf@0.1.5
npm info lifecycle stack-trace@0.0.10~preinstall: stack-trace@0.0.10
npm info lifecycle chownr@1.1.4~preinstall: chownr@1.1.4
npm info lifecycle mkdirp@0.5.5~preinstall: mkdirp@0.5.5
npm info lifecycle pump@1.0.3~preinstall: pump@1.0.3
npm info lifecycle string_decoder@1.1.1~preinstall: string_decoder@1.1.1
npm info lifecycle readable-stream@2.3.7~preinstall: readable-stream@2.3.7
npm info lifecycle bl@1.2.3~preinstall: bl@1.2.3
npm info lifecycle to-buffer@1.1.1~preinstall: to-buffer@1.1.1
npm info lifecycle tar-stream@1.6.2~preinstall: tar-stream@1.6.2
npm info lifecycle tar-fs@1.16.3~preinstall: tar-fs@1.16.3
npm info lifecycle geo-from-ip@2.1.0~preinstall: geo-from-ip@2.1.0
npm info lifecycle targz@1.0.1~preinstall: targz@1.0.1
npm info lifecycle node-fetch@2.6.1~preinstall: node-fetch@2.6.1
npm info lifecycle maxmind-db-reader@0.2.1~preinstall: maxmind-db-reader@0.2.1
npm info lifecycle ip-address@4.0.0~preinstall: ip-address@4.0.0
npm info lifecycle cliff@0.1.10~preinstall: cliff@0.1.10
npm info lifecycle winston@0.8.3~preinstall: winston@0.8.3
npm info lifecycle colors@0.6.2~preinstall: colors@0.6.2
npm info lifecycle async@0.2.10~preinstall: async@0.2.10
npm timing action:preinstall Completed in 166ms
npm info linkStuff big-integer@1.6.48
npm info linkStuff buffer-alloc-unsafe@1.1.0
npm info linkStuff buffer-fill@1.0.0
npm info linkStuff buffer-alloc@1.2.0
npm info linkStuff lru-cache@2.7.3
npm info linkStuff colors@1.0.3
npm info linkStuff cycle@1.0.3
npm info linkStuff eyes@0.1.8
npm info linkStuff fs-constants@1.0.0
npm info linkStuff lodash._arraycopy@3.0.0
npm info linkStuff lodash._arrayeach@3.0.0
npm info linkStuff lodash._basecopy@3.0.1
npm info linkStuff lodash._basefind@3.0.0
npm info linkStuff lodash._basefindindex@3.6.0
npm info linkStuff lodash._basefor@3.0.3
npm info linkStuff lodash._bindcallback@3.0.1
npm info linkStuff lodash._getnative@3.9.1
npm info linkStuff lodash._isiterateecall@3.0.9
npm info linkStuff lodash.isarguments@3.1.0
npm info linkStuff lodash.isarray@3.0.4
npm info linkStuff lodash.istypedarray@3.0.6
npm info linkStuff lodash.keys@3.1.2
npm info linkStuff lodash._baseeach@3.0.4
npm info linkStuff lodash._baseisequal@3.0.7
npm info linkStuff lodash.keysin@3.0.8
npm info linkStuff lodash.isplainobject@3.2.0
npm info linkStuff lodash.pairs@3.0.1
npm info linkStuff lodash._basecallback@3.3.1
npm info linkStuff lodash.find@3.2.1
npm info linkStuff lodash.restparam@3.6.1
npm info linkStuff lodash._createassigner@3.1.1
npm info linkStuff lodash.toplainobject@3.0.0
npm info linkStuff lodash.merge@3.3.2
npm info linkStuff jsbn@0.0.0
npm info linkStuff pkginfo@0.3.1
npm info linkStuff sigmund@1.0.1
npm info linkStuff minimatch@0.3.0
npm info linkStuff glob@3.2.11
npm info linkStuff cli@0.6.6
npm info linkStuff sprintf@0.1.5
npm info linkStuff stack-trace@0.0.10
npm info linkStuff chownr@1.1.4
npm info linkStuff mkdirp@0.5.5
npm verb linkBins [
npm verb linkBins   { mkdirp: 'bin/cmd.js' },
npm verb linkBins   '/Users/gmgallo/Lavoro/Progetti/workspace/Gynnico/gynnicoweb/node_modules/tar-fs/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff pump@1.0.3
npm info linkStuff string_decoder@1.1.1
npm info linkStuff readable-stream@2.3.7
npm info linkStuff bl@1.2.3
npm info linkStuff to-buffer@1.1.1
npm info linkStuff tar-stream@1.6.2
npm info linkStuff tar-fs@1.16.3
npm info linkStuff async@0.2.10
npm info linkStuff colors@0.6.2
npm info linkStuff winston@0.8.3
npm info linkStuff cliff@0.1.10
npm info linkStuff ip-address@4.0.0
npm verb linkBins [
npm verb linkBins   { ipv6: 'bin/ipv6.js', ipv6grep: 'bin/ipv6grep.js' },
npm verb linkBins   '/Users/gmgallo/Lavoro/Progetti/workspace/Gynnico/gynnicoweb/node_modules/maxmind-db-reader/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff maxmind-db-reader@0.2.1
npm verb linkBins [
npm verb linkBins   { 'mmdb-geoip': 'repl' },
npm verb linkBins   '/Users/gmgallo/Lavoro/Progetti/workspace/Gynnico/gynnicoweb/node_modules/.bin',
npm verb linkBins   false
npm verb linkBins ]
npm info linkStuff node-fetch@2.6.1
npm info linkStuff targz@1.0.1
npm info linkStuff geo-from-ip@2.1.0
npm timing action:build Completed in 275ms
npm info lifecycle big-integer@1.6.48~install: big-integer@1.6.48
npm info lifecycle buffer-alloc-unsafe@1.1.0~install: buffer-alloc-unsafe@1.1.0
npm info lifecycle buffer-fill@1.0.0~install: buffer-fill@1.0.0
npm info lifecycle buffer-alloc@1.2.0~install: buffer-alloc@1.2.0
npm info lifecycle lru-cache@2.7.3~install: lru-cache@2.7.3
npm info lifecycle colors@1.0.3~install: colors@1.0.3
npm info lifecycle cycle@1.0.3~install: cycle@1.0.3
npm info lifecycle eyes@0.1.8~install: eyes@0.1.8
npm info lifecycle fs-constants@1.0.0~install: fs-constants@1.0.0
npm info lifecycle lodash._arraycopy@3.0.0~install: lodash._arraycopy@3.0.0
npm info lifecycle lodash._arrayeach@3.0.0~install: lodash._arrayeach@3.0.0
npm info lifecycle lodash._basecopy@3.0.1~install: lodash._basecopy@3.0.1
npm info lifecycle lodash._basefind@3.0.0~install: lodash._basefind@3.0.0
npm info lifecycle lodash._basefindindex@3.6.0~install: lodash._basefindindex@3.6.0
npm info lifecycle lodash._basefor@3.0.3~install: lodash._basefor@3.0.3
npm info lifecycle lodash._bindcallback@3.0.1~install: lodash._bindcallback@3.0.1
npm info lifecycle lodash._getnative@3.9.1~install: lodash._getnative@3.9.1
npm info lifecycle lodash._isiterateecall@3.0.9~install: lodash._isiterateecall@3.0.9
npm info lifecycle lodash.isarguments@3.1.0~install: lodash.isarguments@3.1.0
npm info lifecycle lodash.isarray@3.0.4~install: lodash.isarray@3.0.4
npm info lifecycle lodash.istypedarray@3.0.6~install: lodash.istypedarray@3.0.6
npm info lifecycle lodash.keys@3.1.2~install: lodash.keys@3.1.2
npm info lifecycle lodash._baseeach@3.0.4~install: lodash._baseeach@3.0.4
npm info lifecycle lodash._baseisequal@3.0.7~install: lodash._baseisequal@3.0.7
npm info lifecycle lodash.keysin@3.0.8~install: lodash.keysin@3.0.8
npm info lifecycle lodash.isplainobject@3.2.0~install: lodash.isplainobject@3.2.0
npm info lifecycle lodash.pairs@3.0.1~install: lodash.pairs@3.0.1
npm info lifecycle lodash._basecallback@3.3.1~install: lodash._basecallback@3.3.1
npm info lifecycle lodash.find@3.2.1~install: lodash.find@3.2.1
npm info lifecycle lodash.restparam@3.6.1~install: lodash.restparam@3.6.1
npm info lifecycle lodash._createassigner@3.1.1~install: lodash._createassigner@3.1.1
npm info lifecycle lodash.toplainobject@3.0.0~install: lodash.toplainobject@3.0.0
npm info lifecycle lodash.merge@3.3.2~install: lodash.merge@3.3.2
npm info lifecycle jsbn@0.0.0~install: jsbn@0.0.0
npm info lifecycle pkginfo@0.3.1~install: pkginfo@0.3.1
npm info lifecycle sigmund@1.0.1~install: sigmund@1.0.1
npm info lifecycle minimatch@0.3.0~install: minimatch@0.3.0
npm info lifecycle glob@3.2.11~install: glob@3.2.11
npm info lifecycle cli@0.6.6~install: cli@0.6.6
npm info lifecycle sprintf@0.1.5~install: sprintf@0.1.5
npm info lifecycle stack-trace@0.0.10~install: stack-trace@0.0.10
npm info lifecycle chownr@1.1.4~install: chownr@1.1.4
npm info lifecycle mkdirp@0.5.5~install: mkdirp@0.5.5
npm info lifecycle pump@1.0.3~install: pump@1.0.3
npm info lifecycle string_decoder@1.1.1~install: string_decoder@1.1.1
npm info lifecycle readable-stream@2.3.7~install: readable-stream@2.3.7
npm info lifecycle bl@1.2.3~install: bl@1.2.3
npm info lifecycle to-buffer@1.1.1~install: to-buffer@1.1.1
npm info lifecycle tar-stream@1.6.2~install: tar-stream@1.6.2
npm info lifecycle tar-fs@1.16.3~install: tar-fs@1.16.3
npm info lifecycle async@0.2.10~install: async@0.2.10
npm info lifecycle colors@0.6.2~install: colors@0.6.2
npm info lifecycle winston@0.8.3~install: winston@0.8.3
npm info lifecycle cliff@0.1.10~install: cliff@0.1.10
npm info lifecycle ip-address@4.0.0~install: ip-address@4.0.0
npm info lifecycle maxmind-db-reader@0.2.1~install: maxmind-db-reader@0.2.1
npm info lifecycle node-fetch@2.6.1~install: node-fetch@2.6.1
npm info lifecycle targz@1.0.1~install: targz@1.0.1
npm info lifecycle geo-from-ip@2.1.0~install: geo-from-ip@2.1.0
npm timing action:install Completed in 43ms
npm info lifecycle big-integer@1.6.48~postinstall: big-integer@1.6.48
npm info lifecycle buffer-alloc-unsafe@1.1.0~postinstall: buffer-alloc-unsafe@1.1.0
npm info lifecycle buffer-fill@1.0.0~postinstall: buffer-fill@1.0.0
npm info lifecycle buffer-alloc@1.2.0~postinstall: buffer-alloc@1.2.0
npm info lifecycle lru-cache@2.7.3~postinstall: lru-cache@2.7.3
npm info lifecycle colors@1.0.3~postinstall: colors@1.0.3
npm info lifecycle cycle@1.0.3~postinstall: cycle@1.0.3
npm info lifecycle eyes@0.1.8~postinstall: eyes@0.1.8
npm info lifecycle fs-constants@1.0.0~postinstall: fs-constants@1.0.0
npm info lifecycle lodash._arraycopy@3.0.0~postinstall: lodash._arraycopy@3.0.0
npm info lifecycle lodash._arrayeach@3.0.0~postinstall: lodash._arrayeach@3.0.0
npm info lifecycle lodash._basecopy@3.0.1~postinstall: lodash._basecopy@3.0.1
npm info lifecycle lodash._basefind@3.0.0~postinstall: lodash._basefind@3.0.0
npm info lifecycle lodash._basefindindex@3.6.0~postinstall: lodash._basefindindex@3.6.0
npm info lifecycle lodash._basefor@3.0.3~postinstall: lodash._basefor@3.0.3
npm info lifecycle lodash._bindcallback@3.0.1~postinstall: lodash._bindcallback@3.0.1
npm info lifecycle lodash._getnative@3.9.1~postinstall: lodash._getnative@3.9.1
npm info lifecycle lodash._isiterateecall@3.0.9~postinstall: lodash._isiterateecall@3.0.9
npm info lifecycle lodash.isarguments@3.1.0~postinstall: lodash.isarguments@3.1.0
npm info lifecycle lodash.isarray@3.0.4~postinstall: lodash.isarray@3.0.4
npm info lifecycle lodash.istypedarray@3.0.6~postinstall: lodash.istypedarray@3.0.6
npm info lifecycle lodash.keys@3.1.2~postinstall: lodash.keys@3.1.2
npm info lifecycle lodash._baseeach@3.0.4~postinstall: lodash._baseeach@3.0.4
npm info lifecycle lodash._baseisequal@3.0.7~postinstall: lodash._baseisequal@3.0.7
npm info lifecycle lodash.keysin@3.0.8~postinstall: lodash.keysin@3.0.8
npm info lifecycle lodash.isplainobject@3.2.0~postinstall: lodash.isplainobject@3.2.0
npm info lifecycle lodash.pairs@3.0.1~postinstall: lodash.pairs@3.0.1
npm info lifecycle lodash._basecallback@3.3.1~postinstall: lodash._basecallback@3.3.1
npm info lifecycle lodash.find@3.2.1~postinstall: lodash.find@3.2.1
npm info lifecycle lodash.restparam@3.6.1~postinstall: lodash.restparam@3.6.1
npm info lifecycle lodash._createassigner@3.1.1~postinstall: lodash._createassigner@3.1.1
npm info lifecycle lodash.toplainobject@3.0.0~postinstall: lodash.toplainobject@3.0.0
npm info lifecycle lodash.merge@3.3.2~postinstall: lodash.merge@3.3.2
npm info lifecycle jsbn@0.0.0~postinstall: jsbn@0.0.0
npm info lifecycle pkginfo@0.3.1~postinstall: pkginfo@0.3.1
npm info lifecycle sigmund@1.0.1~postinstall: sigmund@1.0.1
npm info lifecycle minimatch@0.3.0~postinstall: minimatch@0.3.0
npm info lifecycle glob@3.2.11~postinstall: glob@3.2.11
npm info lifecycle cli@0.6.6~postinstall: cli@0.6.6
npm info lifecycle sprintf@0.1.5~postinstall: sprintf@0.1.5
npm info lifecycle stack-trace@0.0.10~postinstall: stack-trace@0.0.10
npm info lifecycle chownr@1.1.4~postinstall: chownr@1.1.4
npm info lifecycle mkdirp@0.5.5~postinstall: mkdirp@0.5.5
npm info lifecycle pump@1.0.3~postinstall: pump@1.0.3
npm info lifecycle string_decoder@1.1.1~postinstall: string_decoder@1.1.1
npm info lifecycle readable-stream@2.3.7~postinstall: readable-stream@2.3.7
npm info lifecycle bl@1.2.3~postinstall: bl@1.2.3
npm info lifecycle to-buffer@1.1.1~postinstall: to-buffer@1.1.1
npm info lifecycle tar-stream@1.6.2~postinstall: tar-stream@1.6.2
npm info lifecycle tar-fs@1.16.3~postinstall: tar-fs@1.16.3
npm info lifecycle async@0.2.10~postinstall: async@0.2.10
npm info lifecycle colors@0.6.2~postinstall: colors@0.6.2
npm info lifecycle winston@0.8.3~postinstall: winston@0.8.3
npm info lifecycle cliff@0.1.10~postinstall: cliff@0.1.10
npm info lifecycle ip-address@4.0.0~postinstall: ip-address@4.0.0
npm info lifecycle maxmind-db-reader@0.2.1~postinstall: maxmind-db-reader@0.2.1
npm info lifecycle node-fetch@2.6.1~postinstall: node-fetch@2.6.1
npm info lifecycle targz@1.0.1~postinstall: targz@1.0.1
npm info lifecycle geo-from-ip@2.1.0~postinstall: geo-from-ip@2.1.0

> geo-from-ip@2.1.0 postinstall /Users/gmgallo/Lavoro/Progetti/workspace/Gynnico/gynnicoweb/node_modules/geo-from-ip
> node lib/update.js

npm verb lifecycle geo-from-ip@2.1.0~postinstall: unsafe-perm in lifecycle true
npm verb lifecycle geo-from-ip@2.1.0~postinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/gmgallo/Lavoro/Progetti/workspace/Gynnico/gynnicoweb/node_modules/geo-from-ip/node_modules/.bin:/Users/gmgallo/Lavoro/Progetti/workspace/Gynnico/gynnicoweb/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS
npm verb lifecycle geo-from-ip@2.1.0~postinstall: CWD: /Users/gmgallo/Lavoro/Progetti/workspace/Gynnico/gynnicoweb/node_modules/geo-from-ip
npm info lifecycle geo-from-ip@2.1.0~postinstall: Failed to exec postinstall script
npm timing action:postinstall Completed in 930ms
npm verb unlock done using /Users/gmgallo/.npm/_locks/staging-a2520ced5a2e0b11.lock for /Users/gmgallo/Lavoro/Progetti/workspace/Gynnico/gynnicoweb/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 911ms
npm timing stage:runTopLevelLifecycles Completed in 90348ms
npm WARN @digitalascetic/ngx-pica@9.0.4 requires a peer of exifr@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-bootstrap/ng-bootstrap@9.1.0 requires a peer of @angular/localize@^11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngu/carousel@3.0.2 requires a peer of @angular/common@^10.0.4 but none is installed. You must install peer dependencies yourself.
npm WARN @ngu/carousel@3.0.2 requires a peer of @angular/core@^10.0.4 but none is installed. You must install peer dependencies yourself.

npm verb stack Error: geo-from-ip@2.1.0 postinstall: `node lib/update.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:315:20)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1048:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid geo-from-ip@2.1.0
npm verb cwd /Users/gmgallo/Lavoro/Progetti/workspace/Gynnico/gynnicoweb
npm verb Darwin 20.4.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "geo-from-ip" "--verbose"
npm verb node v14.15.4
npm verb npm  v6.13.7
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geo-from-ip@2.1.0 postinstall: `node lib/update.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the geo-from-ip@2.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 101481ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gmgallo/.npm/_logs/2021-05-31T07_44_34_083Z-debug.log`

And the library is not installed.

Any idea?

**Comment by YuriiKononenko** [comment]
@gigallo Just run into the same issue. Apparently, MaxMind license key is missing, try `MAXMIND_LICENSE_KEY=your_license_key npm install` after adding dependency into `package.json`

**Comment by SashaDesigN** [comment]
@YuriiKononenko MAXMIND_LICENSE_KEY='my key' worked for me too, I had this error trace:

```
$ npm i geo-from-ip --save
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> geo-from-ip@2.1.0 postinstall D:\ocp-backend\node_modules\geo-from-ip
> node lib/update.js

npm WARN babel-jest@27.4.5 requires a peer of @babel/core@^7.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geo-from-ip@2.1.0 postinstall: `node lib/update.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the geo-from-ip@2.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alex\AppData\Roaming\npm-cache\_logs\2022-10-22T05_43_04_285Z-debug.log


```

**Comment by dnyaneshbqt** [comment]
I am also getting the same issue can you please tell me that how you solved that?
thanks
